### ISSUE TITLE
Crash after the jei update

### ISSUE THREAD

**Issue by SunIAver** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#13] opened 2024-07-18 21:01 UTC
After updating JEI to jei-1.20.1-forge-15.0.10, the mod does not work. It enters the game and then crashes shortly after.

**Comment by gisellevonbingen** [comment] 2024-07-18 22:27
Update mod please

**Comment by mezz** [comment] 2024-07-19 00:02
Duplicate of https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/12

**Closed as not planned** 2024-07-19 01:20 UTC
